# Generated by Django 3.1.1 on 2020-10-17 18:28

from django.db import migrations, models
import serviceScheduleBack.access.models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20200911_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=serviceScheduleBack.access.models.upload_name, verbose_name='Imagem'),
        ),
    ]
