# Generated by Django 3.1.1 on 2020-11-04 23:29

from django.db import migrations, models
import django.db.models.deletion
import serviceScheduleBack.access.models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_perfil_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, default='profile-default', null=True, upload_to=serviceScheduleBack.access.models.upload_name, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.company'),
        ),
    ]
