# Generated by Django 3.1.1 on 2020-09-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Data inicial')),
                ('date_end', models.DateField(verbose_name='Data final')),
                ('hours_start', models.TimeField(verbose_name='Hora inicial')),
                ('hours_end', models.TimeField(verbose_name='Hora Final')),
                ('time_range', models.IntegerField(default=0, verbose_name='Tempo de atendimento')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('week', models.CharField(max_length=7, verbose_name='Semana')),
                ('date', models.DateField(verbose_name='Data')),
                ('hours_start', models.TimeField(verbose_name='Hora inicial')),
                ('hours_end', models.TimeField(verbose_name='Hora Final')),
                ('all_day', models.BooleanField(default=False, verbose_name='Todo dia')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('hour', models.TimeField(verbose_name='Hora')),
                ('canceled_at', models.DateTimeField()),
                ('loose_client', models.CharField(max_length=30, verbose_name='Cliente avulso')),
                ('time_range', models.IntegerField(default=0, verbose_name='Tempo de atendimento')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_provider', to='access.perfil', verbose_name='Provider')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_user', to='access.perfil', verbose_name='Usuário')),
            ],
        ),
    ]
