# Generated by Django 3.1.1 on 2020-09-14 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20200911_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_event', to='schedule.event'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_schedule', to='schedule.schedule'),
        ),
    ]
