# Generated by Django 3.1.1 on 2020-11-04 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auto_20201104_2029'),
        ('schedule', '0007_auto_20200919_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.company'),
        ),
    ]
