# Generated by Django 3.1.1 on 2020-11-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_appointment_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_event', to='schedule.event'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_schedule', to='schedule.schedule'),
        ),
    ]
