# Generated by Django 3.1.1 on 2020-11-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20201105_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Livre'), ('1', 'Agendado'), ('2', 'Ocupado')], default='0', max_length=1, null=True),
        ),
    ]
