# Generated by Django 3.1.1 on 2020-11-14 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auto_20201104_2029'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0010_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Data')),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('loose_client', models.CharField(blank=True, max_length=30, verbose_name='Cliente avulso')),
                ('time_range', models.IntegerField(default=0, verbose_name='Tempo de atendimento')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_appointment_provider', to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canceled_appointment_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
