# Generated by Django 3.1.1 on 2020-12-03 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0011_canceledappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='provider_busy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_provider_busy', to=settings.AUTH_USER_MODEL, verbose_name='Provider Busy'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='send_notification',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Enviar notificação'),
        ),
    ]
